USE [master]
GO

/****** Object:  Database [CFEngine60]    Script Date: 2020-03-18 5:53:35 PM ******/
CREATE DATABASE [CFEngine60]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CFEngine52', FILENAME = N'C:\Toyota DB\CFEngine52.MDF' , SIZE = 5274944KB , MAXSIZE = 34816000KB , FILEGROWTH = 5%), 
 FILEGROUP [Tracefile] 
( NAME = N'Trace', FILENAME = N'C:\Toyota DB\Trace.ndf' , SIZE = 10517824KB , MAXSIZE = 20480000KB , FILEGROWTH = 5%), 
 FILEGROUP [TracefileFast] 
( NAME = N'Trace_fast', FILENAME = N'E:\ToyotaTmp\Trace1.NDF' , SIZE = 0KB , MAXSIZE = 4096000KB , FILEGROWTH = 20%), 
 FILEGROUP [TracefileSlow] 
( NAME = N'Trace_slow', FILENAME = N'E:\ToyotaTmp\Trace2.NDF' , SIZE = 0KB , MAXSIZE = 4096000KB , FILEGROWTH = 20%)
 LOG ON 
( NAME = N'CFEngine52_log', FILENAME = N'C:\Toyota DB\CFEngine52_log.LDF' , SIZE = 12032KB , MAXSIZE = 3174400KB , FILEGROWTH = 20%)
GO

ALTER DATABASE [CFEngine60] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CFEngine60].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CFEngine60] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CFEngine60] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CFEngine60] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CFEngine60] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CFEngine60] SET ARITHABORT OFF 
GO

ALTER DATABASE [CFEngine60] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CFEngine60] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CFEngine60] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CFEngine60] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CFEngine60] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CFEngine60] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CFEngine60] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CFEngine60] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CFEngine60] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CFEngine60] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CFEngine60] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CFEngine60] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CFEngine60] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CFEngine60] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [CFEngine60] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CFEngine60] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CFEngine60] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CFEngine60] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CFEngine60] SET  MULTI_USER 
GO

ALTER DATABASE [CFEngine60] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CFEngine60] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CFEngine60] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CFEngine60] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CFEngine60] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CFEngine60] SET QUERY_STORE = OFF
GO

USE [CFEngine60]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [CFEngine60] SET  READ_WRITE 
GO


