USE [CFEngine60]
GO

/****** Object:  Table [dbo].[DATADOCUMENTXML]    Script Date: 2020-03-18 5:54:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DATADOCUMENTXML](
	[DATADOCUMENTXMLGUID] [uniqueidentifier] NOT NULL,
	[PROCESSENGINEGUID] [uniqueidentifier] NOT NULL,
	[DATADOCUMENTID] [nvarchar](100) NOT NULL,
	[DATADOCUMENTXML] [nvarchar](max) NOT NULL,
	[EXTERNALSTATUS] [varchar](10) NULL,
	[UPDATETIME] [datetime] NULL,
 CONSTRAINT [PK_DataDocumentXml] PRIMARY KEY NONCLUSTERED 
(
	[DATADOCUMENTXMLGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[DATADOCUMENTXML]  WITH CHECK ADD  CONSTRAINT [PE-DataDocumentXml] FOREIGN KEY([PROCESSENGINEGUID])
REFERENCES [dbo].[PROCESSENGINE] ([PROCESSENGINEGUID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[DATADOCUMENTXML] CHECK CONSTRAINT [PE-DataDocumentXml]
GO


