USE [CFEngine60]
GO

/****** Object:  Table [dbo].[PROCESSENGINE]    Script Date: 2020-03-18 5:53:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROCESSENGINE](
	[PROCESSENGINEGUID] [uniqueidentifier] NOT NULL,
	[PROCESSCACHEGUID] [uniqueidentifier] NOT NULL,
	[APPLICATIONID] [int] IDENTITY(1,1) NOT NULL,
	[STARTERUSERID] [nvarchar](50) NOT NULL,
	[CREATIONTIME] [datetime] NOT NULL,
	[STARTERUSERORGANIZATIONGUID] [uniqueidentifier] NOT NULL,
	[STARTERUSERORGANIZATIONPATH] [nvarchar](255) NOT NULL,
	[STARTERUSERASID] [nvarchar](50) NOT NULL,
	[STARTERUSERASORGANIZATIONGUID] [uniqueidentifier] NOT NULL,
	[STARTERUSERASORGANIZATIONPATH] [nvarchar](255) NOT NULL,
	[PROCESSCACHEID] [nvarchar](100) NOT NULL,
	[PROCESSCACHEIDNAME] [nvarchar](100) NOT NULL,
	[PROCESSCACHEIDDESCRIPTION] [nvarchar](100) NOT NULL,
	[VERSIONMAJOR] [int] NOT NULL,
	[VERSIONMINOR] [int] NOT NULL,
	[PROCESSENGINESTATUS] [nvarchar](50) NOT NULL,
	[PROCEDURECACHEGUID] [uniqueidentifier] NOT NULL,
	[PROCEDURECACHEID] [nvarchar](100) NOT NULL,
	[PROCEDURECACHEIDNAME] [nvarchar](100) NOT NULL,
	[PROCEDURECACHEIDDESCRIPTION] [nvarchar](100) NOT NULL,
	[PROCEDUREENGINEGUID] [uniqueidentifier] NOT NULL,
	[ACTIVITYTYPE] [varchar](50) NOT NULL,
	[ACTIVITYCACHEGUID] [uniqueidentifier] NOT NULL,
	[ACTIVITYCACHEID] [nvarchar](100) NOT NULL,
	[ACTIVITYCACHEIDNAME] [nvarchar](100) NOT NULL,
	[ACTIVITYCACHEIDDESCRIPTION] [nvarchar](100) NOT NULL,
	[ACTIVITYENGINEGUID] [uniqueidentifier] NOT NULL,
	[ACTIVITYENGINEEXITCONNECTION] [nvarchar](50) NOT NULL,
	[PHASECACHEGUID] [uniqueidentifier] NOT NULL,
	[PHASECACHEID] [nvarchar](100) NOT NULL,
	[PHASECACHEIDNAME] [nvarchar](100) NOT NULL,
	[PHASECACHEIDDESCRIPTION] [nvarchar](100) NOT NULL,
	[BUSINESSFIELD1] [nvarchar](400) NULL,
	[BUSINESSFIELD2] [nvarchar](400) NULL,
	[OWNERUSERID] [nvarchar](50) NOT NULL,
	[OWNERUSERORGANIZATIONGUID] [uniqueidentifier] NOT NULL,
	[OWNERUSERORGANIZATIONPATH] [nvarchar](255) NOT NULL,
	[CURRENTUSERID] [nvarchar](50) NOT NULL,
	[CURRENTUSERORGANIZATIONGUID] [uniqueidentifier] NOT NULL,
	[CURRENTUSERORGANIZATIONPATH] [nvarchar](255) NOT NULL,
	[PRIORITY] [int] NOT NULL,
	[ISRUNNING] [bit] NOT NULL,
	[STOPTIME] [datetime] NOT NULL,
	[LASTUPDATETIME] [datetime] NOT NULL,
	[UPDATERROLEID] [nvarchar](50) NULL,
	[LOCKUSERID] [nvarchar](50) NULL,
	[LOCKTIME] [datetime] NULL,
	[DISPATCHDATE] [datetime] NULL,
	[ECMENABLED] [bit] NOT NULL,
	[ECMLINK] [nvarchar](255) NULL,
	[PHASEFLOWGUID] [uniqueidentifier] NULL,
	[PHASEFLOWID] [nvarchar](100) NULL,
	[PHASEFLOWIDNAME] [nvarchar](100) NULL,
	[PHASEFLOWIDDESCRIPTION] [nvarchar](100) NULL,
	[ISARCHIVED] [bit] NULL,
 CONSTRAINT [PK_ProcessEngine] PRIMARY KEY NONCLUSTERED 
(
	[PROCESSENGINEGUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PROCESSENGINE] ADD  CONSTRAINT [DF_ProcessEngine_CreationTime]  DEFAULT (getdate()) FOR [CREATIONTIME]
GO

ALTER TABLE [dbo].[PROCESSENGINE] ADD  CONSTRAINT [DF_ProcessEngine_Priority]  DEFAULT ((3)) FOR [PRIORITY]
GO

ALTER TABLE [dbo].[PROCESSENGINE] ADD  CONSTRAINT [DF_ProcessEngine_IsRunning]  DEFAULT ((0)) FOR [ISRUNNING]
GO

ALTER TABLE [dbo].[PROCESSENGINE] ADD  CONSTRAINT [DF_ProcessEngine_StopTime]  DEFAULT (getdate()) FOR [STOPTIME]
GO

ALTER TABLE [dbo].[PROCESSENGINE] ADD  CONSTRAINT [DF_ProcessEngine_LastUpdateTime]  DEFAULT (getdate()) FOR [LASTUPDATETIME]
GO

ALTER TABLE [dbo].[PROCESSENGINE] ADD  CONSTRAINT [DF_PROCESSENGINE_ECMENABLED]  DEFAULT ((0)) FOR [ECMENABLED]
GO

ALTER TABLE [dbo].[PROCESSENGINE] ADD  CONSTRAINT [DF_PROCESSENGINE_ISARCHIVED]  DEFAULT ((0)) FOR [ISARCHIVED]
GO

ALTER TABLE [dbo].[PROCESSENGINE]  WITH CHECK ADD  CONSTRAINT [PC-ProcessEngine] FOREIGN KEY([PROCESSCACHEGUID])
REFERENCES [dbo].[PROCESSCACHE] ([PROCESSCACHEGUID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PROCESSENGINE] CHECK CONSTRAINT [PC-ProcessEngine]
GO

ALTER TABLE [dbo].[PROCESSENGINE]  WITH CHECK ADD  CONSTRAINT [CK_ProcessPriority] CHECK  (([Priority]>=(0) AND [Priority]<=(5)))
GO

ALTER TABLE [dbo].[PROCESSENGINE] CHECK CONSTRAINT [CK_ProcessPriority]
GO


