USE [master]
GO

/****** Object:  Database [Engine]    Script Date: 20.03.2020 16:23:40 ******/
CREATE DATABASE [Engine]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Engine', FILENAME = N'D:\ENGINE\Engine.mdf' , SIZE = 102400KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Engine_log', FILENAME = N'D:\ENGINE\Engine_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Engine].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Engine] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Engine] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Engine] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Engine] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Engine] SET ARITHABORT OFF 
GO

ALTER DATABASE [Engine] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Engine] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Engine] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Engine] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Engine] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Engine] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Engine] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Engine] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Engine] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Engine] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Engine] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Engine] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Engine] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Engine] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Engine] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Engine] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Engine] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Engine] SET RECOVERY FULL 
GO

ALTER DATABASE [Engine] SET  MULTI_USER 
GO

ALTER DATABASE [Engine] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Engine] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Engine] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Engine] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Engine] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Engine] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Engine] SET  READ_WRITE 
GO


