USE Engine;
GO
DROP TABLE IF EXISTS dbo.PROCESSCACHE;

CREATE TABLE dbo.PROCESSCACHE(
	PROCESSCACHEID int NOT NULL,
	PROCESSCACHEIDNAME nvarchar(100) NOT NULL,
	PROCESSCACHEIDDESCRIPTION nvarchar(100) NOT NULL,
	VERSIONMAJOR int NOT NULL,
	VERSIONMINOR int NOT NULL,
 CONSTRAINT PK_ProcessCache PRIMARY KEY NONCLUSTERED 
(
	PROCESSCACHEID ASC
) WITH (PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO