USE Engine;
GO
DROP TABLE IF EXISTS dbo.PROCESSENGINE;

CREATE TABLE dbo.PROCESSENGINE(
	PROCESSENGINEID int NOT NULL,
	PROCESSCACHEID int NOT NULL,
	APPLICATIONID int IDENTITY(1,1) NOT NULL,
	CREATIONTIME datetime NOT NULL,
	PROCESSENGINESTATUS nvarchar(50) NOT NULL,
	PHASECACHEID int NOT NULL,
	ISRUNNING bit NOT NULL,
	STOPTIME datetime NOT NULL,
	LASTUPDATETIME datetime NOT NULL,
 CONSTRAINT PK_ProcessEngine PRIMARY KEY NONCLUSTERED 
(
	PROCESSENGINEID ASC
) WITH (PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO

ALTER TABLE dbo.PROCESSENGINE ADD CONSTRAINT DF_ProcessEngine_CreationTime DEFAULT (getdate()) FOR CREATIONTIME;
GO

ALTER TABLE dbo.PROCESSENGINE ADD CONSTRAINT DF_ProcessEngine_PhaseCache DEFAULT ((0)) FOR PHASECACHEID;
GO

ALTER TABLE dbo.PROCESSENGINE ADD CONSTRAINT DF_ProcessEngine_IsRunning  DEFAULT ((0)) FOR ISRUNNING;
GO

ALTER TABLE dbo.PROCESSENGINE ADD CONSTRAINT DF_ProcessEngine_StopTime  DEFAULT (getdate()) FOR STOPTIME;
GO

ALTER TABLE dbo.PROCESSENGINE ADD CONSTRAINT DF_ProcessEngine_LastUpdateTime  DEFAULT (getdate()) FOR LASTUPDATETIME;
GO

ALTER TABLE dbo.PROCESSENGINE WITH CHECK ADD CONSTRAINT PC_ProcessEngine FOREIGN KEY(PROCESSCACHEID)
REFERENCES dbo.PROCESSCACHE (PROCESSCACHEID)
ON DELETE CASCADE;
GO

ALTER TABLE dbo.PROCESSENGINE CHECK CONSTRAINT PC_ProcessEngine
GO

ALTER TABLE dbo.PROCESSENGINE WITH CHECK ADD CONSTRAINT PC_PhaseCache FOREIGN KEY(PHASECACHEID)
REFERENCES dbo.PHASECACHE (PHASECACHEID)
ON DELETE SET DEFAULT;
GO

ALTER TABLE dbo.PROCESSENGINE CHECK CONSTRAINT PC_ProcessEngine
GO

IF EXISTS (SELECT name from sys.indexes  
           WHERE name = N'IX_Engine_ApplicationID')   
   DROP INDEX IX_Engine_ApplicationID ON Production.UnitMeasure;   
GO  
  
CREATE UNIQUE INDEX IX_Engine_ApplicationID   
   ON dbo.PROCESSENGINE (APPLICATIONID);   
GO  