USE Engine;
GO
DROP TABLE IF EXISTS dbo.PHASECACHE;

CREATE TABLE dbo.PHASECACHE(
	PHASECACHEID int NOT NULL,
	PHASECACHEIDNAME nvarchar(100) NOT NULL,
	PHASECACHEIDDESCRIPTION nvarchar(100) NOT NULL,
 CONSTRAINT PK_PhaseCache PRIMARY KEY NONCLUSTERED 
(
	PHASECACHEID ASC
) WITH (PAD_INDEX = OFF, 
		STATISTICS_NORECOMPUTE = OFF, 
		IGNORE_DUP_KEY = OFF, 
		ALLOW_ROW_LOCKS = ON, 
		ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];
GO